name: build-lilyfin-beta
on:
  schedule:
    - cron: "05 10 * * *" # 10:05am UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      tag: beta
      source_tag: beta

  build_cosmic:
    name: Build COSMIC image
    needs: [build]
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      containerfile: "Containerfile.cosmic"
      image_suffix: "-cosmic"
      tag: beta
      source_image: "${{ github.repository_owner }}/${{ github.event.repository.name }}"
      source_tag: beta
